recipe: default.v1
assistant_id: 20251027-233458-linear-render
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 25
    constrain_similarities: true
  - name: EntitySynonymMapper

policies:
  - name: RulePolicy
  - name: MemoizationPolicy
